before_install:
  - npm i -g npm@latest

install:
  - npm ci

after_success: 'npm run coveralls'
language: node_js

sudo: false

node_js:
  - "10"

env:
    global:
        - NODE_ENV=test
cache:
    directories:
        - node_modules
